spring:
  datasource:
    url: jdbc:mysql://localhost:3306/srm?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456

  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 15
      client-name: Redis

logging:
  level:
    com.srm: debug
    org.springframework.security: debug
